server:
  port: 8080
  url: http://localhost:${server.port}


application:
  name: Gateway
  basepath: gateway
  
accounts:
  base-url: https://app-accounts-0434b53c81ce.herokuapp.com/accounts
  create-account: account/create-account
  user-info: customer/user-info

transactions:
  base-url: https://app-transactions-665026f5a398.herokuapp.com/transactions
  create-transaction: transaction/create-transaction
  transaction-history: transaction/history
